services:
  db:
    image: andrplko/nodejs2024q1-service-db:latest
    restart: always
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - my_network
  app:
    image: andrplko/nodejs2024q1-service-app:latest
    restart: always
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: application
    environment:
      DATABASE_HOST: ${POSTGRES_HOST}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - my_network
volumes:
  db-data:
networks:
  my_network:
    driver: bridge